#Checks updates for dependencies daily

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "gradle"
    directory: "app"
    schedule:
      interval: "daily"
    target-branch: "develop"
    open-pull-requests-limit: 7
